name: Deploy to GH-pages

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        strategy:
            matrix:
                node-version: [17.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Build using yarn script
              run: |
                  rm -rf node_modules
                  yarn install --frozen-lockfile
                  yarn run build --if-present
            - name: Deploy to gh-pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build
